### ISSUE TITLE
How it works ?

### ISSUE THREAD

**Issue by 0xtlt** [KodingDev/JetBrainsCopilot#1]
Already, thank you for offering this plugin, it's absolutely awesome.

Now I have it installed, configured with the token and everything that goes with it but I don't have any additional auto-completion.

Are there any other parameters to fill in?

**Comment by KodingDev** [comment]
At the moment it's fairly iffy when it comes to when it completes.
Personally I've found it struggles to start new lines and needs a bit of info before it, not sure if that's an IntelliJ limitation or GitHub Copilot limitation right now.

One thing you should check is if the completions are there, but just showing at the bottom of your autocomplete, which I've had some issues with when wrestling with the IntelliJ SDK.
In general though, completions should work in an instance like this:

```java
// Print hello world
System.out.pr // Rest would be code completed
```

**Comment by 0xtlt** [comment]
I tried and it doesn't work at all on my javascript files

**Comment by 0xtlt** [comment]
Okay it finally worked, not optimal but working, good job :)

**Comment by Trackhe** [comment]
> Okay it finally worked, not optimal but working, good job :)

how you get it working?

**Comment by rlnt** [comment]
Feels like a Stackoverflow getting closed with "nvm I fixed it" but not explaining how.

**Comment by 0xtlt** [comment]
haha sorry guys, I didn't see the notification!
To use Github Copilot on Jetbrain, you need to do 2 things, anyway I'll describe my steps to get it working properly:
- In your IDE settings, there is a place called "Github Copilot" that you can search with the search input.
- In this place, you'll have to go to the link to generate a new token, a token that will be represented by a full vscode URL and not just a usual small token.
- You will have to copy and paste it in the input and validate

that was for setup the extension, now to use it, it's less simple than using the official vscode extension because you'll have to press your shortcut keys to display the "smart" suggestions, sometimes you have to do 2 times in a row the shortcut to get the github copilot suggestions.

After I can't say much more because I used it for 2 days and then I went back to VSCode with the native support, but already this plugin is a good start :)

I hope I could help you!

@Trackhe

**Comment by rlnt** [comment]
The GitHub CEO posted on Twitter that they are already working on an official plugin and he mentioned that it should be ready within the next weeks.

Lookin forward to it.

**Comment by KodingDev** [comment]
Didn't see that, looking forward to it!
Honestly I didn't expect this repo to even gain such traction, was made as a quick hack because I essentially need IntelliJ for working with Kotlin for my job.
Exciting stuff!

**Comment by Trackhe** [comment]
I have read it too on twitter but i cant wait to test it in intellij/webstorm ^^

**Comment by JonasTheGamer** [comment]
Hey, just commenting on this. Which shortcut do I use to show the suggestions? Can I find a manual for this somewhere? :-) Thank you in advance!
